- name: Update Cisco ASA object-group
  hosts: oldvpn_asa
  gather_facts: no
  connection: local

  tasks:
    - name: Updating the object-group
      asa_config:
        parents: ['object-group network apple_srv']
        lines: "{{ item }}"
      with_lines: cat /home/boby/asa_test/dns
        
